### ISSUE TITLE
Build fails on FreeBSD systems

### ISSUE THREAD

**Issue by eserte** [hoytech/Alien-LMDB#1]
Two things:
- The build seems to require GNU make, so on FreeBSD systems (and maybe on other non-Linux systems) "gmake" should be used explicitly. Maybe using Alien::gmake can help here.
- On freebsd 10 and later, there's no gcc by default installed (clang is the default compiler). So using gcc does not work. This can be fixed by calling

```
'gmake -C libraries/liblmdb/ CC=cc'
```

**Comment by hoytech** [comment]
Thanks for the report!

Should hopefully be fixed in this commit:

https://github.com/hoytech/Alien-LMDB/commit/532a3edaa23843cfe7c81cd7764d799fce7dbbab

And in Alien::LMDB 0.102 which I've just sent off to CPAN.

**Comment by hoytech** [comment]
Seems to be OK on FreeBSD:

http://matrix.cpantesters.org/?dist=Alien-LMDB+0.102
